export const SCREENS = {
  SPLASH: "Splash",
  INTRO: "Intro",
  AUTH: "Auth",
  OTPVERIFY: "OtpVerify",
  HOME: "Home",
  CATAGORY: "Catagory",
  ORDERS: "Orders",
  CART: "Cart",
  PROFILE: "Profile",
  PRODUCTDETAILS: "ProductDetails",
  WELCOME: "Welcome",
  WALLET: "Wallet",
  ADDRESS: "Address",
  ACCOUNTANDPRIVACY: "AccountAndPrivacy",
  CUSTOMERSUPPORT: "CustomerSupport",
  NOTIFICATION: "Notification",
  ORDERSSUMMARY: "Orders_Summary",
  ABOUTUS: "Aboutus",
};
